services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hydroadmin
      POSTGRES_PASSWORD: hydropass
      POSTGRES_DB: hydroponics
      PGDATA: /data/postgres
    volumes:
      - ./data/postgres:/data/postgres
    restart: unless-stopped

  mongodb:
    image: mongo:4.4.18
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
    restart: unless-stopped
